on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ hashFiles('./scripts/install.sh') }}
          path: ~/.cargo/bin
      - uses: actions-rs/toolchain@v1
        if: ${{ ! steps.cache.outputs.cache-hit }}
        with:
          toolchain: stable
      - run: make test
