on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      # TODO make use of cache to install stylua
      # - uses: actions/cache@v3
      #   with:
      #     key: ${{ hashFiles('./Makefile') }}
      #     path: 
      - run: echo ${{ hashFiles('./Makefile') }}
      - run: make test
      - run: which stylua
